final ful2en = [''];

List<String> titlesFululde = [
  "Yesu yidi bikkon fu",
  "Dum seyo tokkago lawol",
  "Jodago ha kosde yesu",
  "Sobabe ngurte ha nder nyibre",
  "Baba cenido",
  "Mi don teddina ma allah",
  "Yesu krist don wanca be am",
  "Wodi sobajo am yesu",
  "Yeesu mayi ha gafingal",
  "Nda lekkita manga wari",
  "Baba mi yidi ma",
  "Bana mi woni aybejo",
  "wala sobajo buran yeesu",
  "Mi yidi yalade sabba",
  "Yeesu krist badita hande",
  "Sondu ha ladde",
  "Gafingal yeesu krist",
  "Duniyaru ndu mere",
  "Baddi be yeesu krist",
  "Labinol bernde",
  "War ha yeesu",
  "Baba am don yila be am",
  "Wodi lesdi ha allahhira",
  "Boyma mi anda kisnowo",
  "Gafingal yeesu",
  "Yeesu kisnowo kibuudo",
  "Minin ngidi dowtare",
  "Biddo allah",
  "Yeesu yidi yam",
  "Jodu be am",
  "Tapare duminde",
  "Yeesu badi wartugo",
  "Ha nder asaman",
  "Burdum ha yeesu",
  "Yeesu kisnowo yam",
  "Teddingo allah",
  "Ummatore yimbe allah",
  "Yeesu gainako boddo",
  "Timminol sodol",
  "Mobture hisnabe",
  "Allah jodida be ma",
  "Hubar mbelka",
  "Be siru",
  "Hakke am hosama gal kisnowo",
  "Yeesu be kisnowo",
  "Yimre nyalade sabbat",
  "Ngade zakka",
  "Endam yajaumirawo yeesu-krist",
  "Ruuhu cenido",
  "Berniwol seningol ha asaman",
  "Wartol yeesu nder wudare",
  "Zunubajo bana mi wa’i",
  "Boddumji don har ma ",
  "Jodibe ha lesdi fu",
  "Deftere allah lati jayngol",
  "Allah ewni ma ",
  "Gaynako boddo ",
  "Tokken lawol be gorgaku ",
  "To wodi yide ha sare  ",
  "Yeesu, mi tokkete toye fu",
  "Min ngari ha sudu mada ",
  "Mi yetti ngam yide baba be yeesu ",
  "Moye hisnata duniyaru  ",
  "Kugal mada lati bodngal ",
  "Yeesu jodan cakka meden",
  "Hokku en ruhu mada",
  "Sukka ma wari ",
  "Wi’i fu ha yeesu",
  "Tokkago lawol gongaku",
  "Baba jogam",
  "Sembe don nder yiam yeesu",
  "Ya jawmirawo mi yenwi ma",
  "Mi woni jayngol ma",
  "Lawol kisndam",
  "Ngam ma mi wadi dum",
  "War ha baba hande",
  "Endam kisnowo yam",
  "Ha dukki wade min latan aman’en",
  "Sanya pukarajo",
  "Mi don tefa jam be endam",
  "Mi don be mada",
  "Zunubajo mi hurgete",
  "Sawtu yeesu don noddi yam",
  "Barka kisnowo yeesu-krist",
  "Nyalade fu nder ngendam am ",
  "Bangte ko’e mon",
  "Balde fumi mari haje ma",
  "Dande yeesu don ewna min",
  "Yedgo be yeesu ha asaman",
  "Mi hebi seyo ha kisnowo",
  "Mi don wara jaumirawo",
  "Yimre suwam ",
  "Bernde men seyake ngam yeesu",
  "En mayan hideko ngeden",
  "Mo’ere yeesu",
  "Babirawo allah",
  "Mi don haba habre wonde",
  "Babare fu ha yeesu krist",
  "Mi numan foroy ha allah ",
  "Teffe gikku nbongu",
  "War ha yeesu",
  "To hendu saatundu wadi",
  "A yobi kisdam am bee sadaka",
  "Nda yesu kisnowo men ",
  "To a linyi taaku maada ",
  "Dum seyo mango haa am ",
  "Nder juude ma mi halfini",
];

List<String> titlesEnglish = [
  'Watchman Blow The Gospel Trumpet.',
  'The Coming King',
  'Face To Face',
  'He is Coming',
  'How Far From Home?',
  'Watch Ye Saints',
  'When He Cometh',
  'When the Roll is Called Up Yonder',
  'Jesus is Coming Again',
  'Shall We Gather At The River',
  'I Will Follow Thee',
  'There Is A Fountain',
  'Whiter Than Snow',
  'Hear The Pennies Dropping',
  'Jesus Loves Me',
  'I Washed My Hands',
  'Tis Love That Makes Us Happy',
  'Onward Christian Soldiers',
  'My Soul Be On Thy Guard',
  'Awake, My Soul',
  'I am Coming to the Cross',
  'Lord I Hear',
  "Hover O'er Me, Holy Spirit",
  'I Need The Every Hour',
  'All to Jesus I Surrender',
  'Just As I Am',
  'We Praise Thee, O God',
  'Take Time To Be Holy',
  'Abide With Me',
  'Day is Dying in the West',
  'Sun of My Soul',
  "The Lord's Our Rock",
  'He Leadeth Me',
  'When Peace Like a River',
  'What a Fellowship',
  'My Faith Looks Up to Thee',
  'Nearer, My God to Thee',
  'Stand on The Rock',
  'My Hope is Built',
  'Trust and Obey',
  'God be With You',
  "We'll Never say Goodbye",
  'Asleep in Jesus',
  'When my Life-Work is Ended',
  'Give me The Bible',
  'Sing Them Over Again to Me',
  "On Jordan's Stormy Banks",
  'Joy By And By',
  'One Sweetly Solemn Thought',
  'Sweet By and By',
  'Baptize Us Anew',
  'Come, Thou Fount of Every Blessing',
  'Holy Spirit, Faithful Guide',
  'One thing I of the Lord Desire',
  'Are You Washed in The Blood?',
  "Lord, I'm Coming Home",
  'Whosoever Heareth',
  'All Hail the Power of Jesus Name',
  'Jesus, Lover Of My Soul',
  'Jesus, Thou Joy of Loving Hearts',
  'More About Jesus',
  'My Jesus I Love Thee',
  'What Can Wash Away My Sin?',
  'Tell it To Jesus',
  "'Tis So Sweet to Trust In Jesus",
  'Happy Day',
  'Come We That Love The Lord',
  'Redeemed! How I Love to Proclaim it!',
  "We'll Tarry By The Living Waters",
  'When Jesus Shall Gather',
  'Is My Name Written There?',
  'The Judgement Has Set',
  'Called to the Feast',
  'Sowing in the Morning',
  "Hark! 'Tis The Shepherds Voice",
  'Rescue the Perishing',
  'I Love to Tell the Story',
  'Seeking the Lost',
  'Far and Near',
  'To the Work!',
  'Work, For The Night is Coming',
  'Lord, In the Morning',
  'O For a Thousand Tongues to Sing',
  'Singing As We Journey',
  'I Sing the Mighty Power',
  'O Worship the King',
  'Father, We Come to Thee',
  'Pass me Not, O Gentle Savior',
  'Sweet Hour of Prayer',
  "Another Six Days' Work",
  'Watch, For the Time is Short',
  "Don't Forget the Sabbath",
  'Day of Rest and Gladness',
  'Sweet Sabbath School',
  'Safely Through Another Week',
  'Welcome, Welcome, Day of Rest',
  'Jesus Saves',
  'I Must Have The Savior With Me',
  'When I Survey The Wondrous Cross',
  'What a Friend We Have in Jesus',
  'Jesus is Calling',
  'Let Him In',
  'Ye Must Be Born Again',
  'Come, Great Deliver, Come',
  'Able to Deliver',
  'Build on The Rock',
  'Tell Me The Story of Jesus',
  'Lovingly, Tenderly Calling',
  'Weighed and Wanting',
  'Blessed Are They That Do',
  'No, Not One',
  'Life In A Look',
  'Softly and Tenderly',
  'The Gate Ajar For Me',
  'The Great Physician Now is Near',
  'Nothing for Jesus',
  'I Am Coming, Lord',
  'Jesus Paid It All',
  'The Cleansing Wave',
  'I Do Believe',
  'I Will Sing of Jesus Love',
  'Nearer, Still Nearer',
  'The Holiest Name',
  'Not I, But Christ',
  'Sunlight In The Heart',
  'Since I Have Been Redeemed',
  'He Loves, Me Too',
  'Blessed Hour Of Prayer',
  'Jesus, Come and Bless Us',
  'I Am Thine, O Lord',
  'More Like Jesus',
  'Near the Cross',
  'O Let Me Walk',
  'Wonderful Love of Jesus',
  'I Love Thee Better, Lord',
  'I Remember Calvary',
  'Give Me Jesus',
  'Take My Life',
  "I've Found a Friend",
  'The Voice of Jesus',
  'Wholly Thine',
  'How Sweet',
  'Lord Dismiss Us',
  'Higher Ground',
  'As Not to Be Excused',
  'Thy Life Within Me',
  'Draw Me Closer to Thee',
  'Anywhere with Jesus',
  'Walk in the Light',
  'Where are the Reapers?',
  'Will There Be Any Stars?',
  'Speak To My Soul',
  'Just For Today',
  'Watchman, Tell Me',
  "I'll Go Where you Want me to Go",
  'Angry Words! Oh Let them Never',
  'Harvest Time',
  'Hasten On, Glad Day',
  'How Much I Need Thee',
  'Kept For Jesus',
  'My Lord And I',
  'All The Way',
  'Here Am I, Send Me',
  'At the Feet of Jesus',
  'I Love Thee',
  'Rock Of Ages',
  'Firm Foundation',
  'The Lord Is My Shepherd',
  'Heir of The Kingdom',
  'My Maker and My King',
  'What Of The Night?',
  'How Long?',
  'How Cheering!',
  'O For A Faith',
  'Savior, Like a Shepherd',
  'Blessed Hope',
  'No Night There',
  'Christ Returneth',
  'Behold the Bridegroom',
  'We Know Not the Hour',
  'Waiting and Watching',
  'Gleams Of The Golden Morning',
  'Hold Fast Till I Come',
  'Joy to the World',
  'To be There',
  'Lord We Have Met',
  'Our Parting Hymn',
  'Chief of Sinners',
  'No Abiding City',
  'Take the Name',
  'Blessed Assurance',
  'Glory to His Name',
  'His Way With Thee',
  'Love at Home',
  'O For That Flame',
  'Power In The Blood',
  "There'll be No Dark Valley",
  'The Best Friend is Jesus',
  'To God Be The Glory',
  'Holy, Holy, Holy',
  'He Brought Me Out',
  'Jesus, Savior, Pilot Me',
  'The Comforter Has Come',
  'Welcome! Wonderer Come!',
  'While Jesus Whispers',
  'I Gave My Life For Thee',
  'Seals My Pardon',
  'Tread Softly',
  'A Closer Walk',
  'What a Wonderful Savior',
  'Showers of Blessing',
  'Sweet Peace',
  'My Song',
  'Does Jesus Care?',
  'Wait, And Murmur Not',
  'Never Alone',
  'Something For Jesus',
  'One Foundation',
  'Guide Me, O Thou Great Jehovah',
  'The Homeland',
  'Memories of Galilee',
  'Safe in The Arms of Jesus',
  'Follow All The Way',
  'Let the Lower Lights be Burning',
  'Stand Like the Brave',
  'Almost Persuaded',
  'At the Cross',
  'Praise Him! Praise Him',
  "Who is On the Lord's Side",
  'I Am The Way',
  'Let Jesus Come Into Your Heart',
  'I Will Never Leave Thee',
  'Tell Me The Old, Old Story',
  'Jesus, The Light of The World',
  'Again The Day Returns',
  'His Loving Kindness',
  'Stand Up For Jesus',
  'Who, Who Are These?',
  'Art Thou Weary',
  'At The Door',
  'Beulah Land',
  'Blest Be The Tie',
  'Arise, My Soul, Arise!',
  'Come To Jesus',
  'No Other Name',
  'Now Just A Word',
  'Ring the Bells of Heaven',
  'Jesus of Nazareth Passeth By',
  'The Ninety and Nine',
  'Yield Not to Temptation',
  'Weeping Will not Save Me',
  'Only Trust Him',
  "See, Israel's Gentle Shepherd",
  "Praise Ye Jehovah's Name",
  'I Need Thee, Precious Jesus',
  'O, God Our Help',
  'Unshaken As The Sacred Hills',
  'One Living Faith',
  'Shall We Meet',
  'Vale of Beulah',
  'Beautiful Valley of Eden',
  'Christ or Barabbas',
  'Bring Ye All the Tithes',
  "Holy Day, Jehovah's Rest",
  'Peace, Perfect Peace',
  'Jesus, I will Follow Thee',
  'Scatter Seeds of Kindness',
  'Master, The Tempest is Raging!',
  'A Wonderful Savior',
  'Our Blessed Redeemer',
  "Tho' Your Sins Be As Scarlet",
  'Throw Out the Lifeline',
  'Lean On The Arms',
  'I Have a Savior',
  'Eternity! Where?',
  'Seeking For Me',
  'Lead Kindly Light',
  'Not My Way',
  'Come unto Me',
  'Our King',
  'A Beautiful Star',
  'Ten Thousand Harps',
  'Shall You Shall I?',
  'While the Days Are Going By',
  'There is a Place of Quiet Rest',
  'Bear me On',
  'In the Hour of Trial',
  'They Brought Their Gifts to Jesus',
  'Take Me as I am',
  'Toiling for Jesus',
  'Worthy, Worthy, Is The Lamb',
  'Two Little Hands',
  'Knocking, Knocking',
  'Cover With His Life',
  'Sound the Battle Cry',
  'Lead Me, Savior',
  'Nailed to the Cross',
  'None of Self and All of Thee',
  'Always Cheerful',
  'Rest For the Weary'
];
