List<String> titlesFul = [
  "Yesu yidi bikkon fu",
  "Dum seyo tokkago lawol",
  "Jodago ha kosde yesu",
  "Sobabe ngurte ha nder nyibre",
  "Baba cenido",
  "Mi don teddina ma allah",
  "Yesu krist don wanca be am",
  "Wodi sobajo am yesu",
  "Yeesu mayi ha gafingal",
  "Nda lekkita manga wari",
  "Baba mi yidi ma",
  "Bana mi woni aybejo",
  "wala sobajo buran yeesu",
  "Mi yidi yalade sabba",
  "Yeesu krist badita hande",
  "Sondu ha ladde",
  "Gafingal yeesu krist",
  "Duniyaru ndu mere",
  "Baddi be yeesu krist",
  "Labinol bernde",
  "War ha yeesu",
  "Baba am don yila be am",
  "Wodi lesdi ha allahhira",
  "Boyma mi anda kisnowo",
  "Gafingal yeesu",
  "Yeesu kisnowo kibuudo",
  "Minin ngidi dowtare",
  "Biddo allah",
  "Yeesu yidi yam",
  "Jodu be am",
  "Tapare duminde",
  "Yeesu badi wartugo",
  "Ha nder asaman",
  "Burdum ha yeesu",
  "Yeesu kisnowo yam",
  "Teddingo allah",
  "Ummatore yimbe allah",
  "Yeesu gainako boddo",
  "Timminol sodol",
  "Mobture hisnabe",
  "Allah jodida be ma",
  "Hubar mbelka",
  "Be siru",
  "Hakke am hosama gal kisnowo",
  "Yeesu be kisnowo",
  "Yimre nyalade sabbat",
  "Ngade zakka",
  "Endam yajaumirawo yeesu-krist",
  "Ruuhu cenido",
  "Berniwol seningol ha asaman",
  "Wartol yeesu nder wudare",
  "Zunubajo bana mi wa’i",
  "Boddumji don har ma ",
  "Jodibe ha lesdi fu",
  "Deftere allah lati jayngol",
  "Allah ewni ma ",
  "Gaynako boddo ",
  "Tokken lawol be gorgaku ",
  "To wodi yide ha sare  ",
  "Yeesu, mi tokkete toye fu",
  "Min ngari ha sudu mada ",
  "Mi yetti ngam yide baba be yeesu ",
  "Moye hisnata duniyaru  ",
  "Kugal mada lati bodngal ",
  "Yeesu jodan cakka meden",
  "Hokku en ruhu mada",
  "Sukka ma wari ",
  "Wi’i fu ha yeesu",
  "Tokkago lawol gongaku",
  "Baba jogam",
  "Sembe don nder yiam yeesu",
  "Ya jawmirawo mi yenwi ma",
  "Mi woni jayngol ma",
  "Lawol kisndam",
  "Ngam ma mi wadi dum",
  "War ha baba hande",
  "Endam kisnowo yam",
  "Ha dukki wade min latan aman’en",
  "Sanya pukarajo",
  "Mi don tefa jam be endam",
  "Mi don be mada",
  "Zunubajo mi hurgete",
  "Sawtu yeesu don noddi yam",
  "Barka kisnowo yeesu-krist",
  "Nyalade fu nder ngendam am ",
  "Bangte ko’e mon",
  "Balde fumi mari haje ma",
  "Dande yeesu don ewna min",
  "Yedgo be yeesu ha asaman",
  "Mi hebi seyo ha kisnowo",
  "Mi don wara jaumirawo",
  "Yimre suwam ",
  "Bernde men seyake ngam yeesu",
  "En mayan hideko ngeden",
  "Mo’ere yeesu",
  "Babirawo allah",
  "Mi don haba habre wonde",
  "Babare fu ha yeesu krist",
  "Mi numan foroy ha allah ",
  "Teffe gikku nbongu",
  "War ha yeesu",
  "To hendu saatundu wadi",
  "A yobi kisdam am bee sadaka",
  "Nda yesu kisnowo men ",
  "To a linyi taaku maada ",
  "Dum seyo mango haa am ",
  "Nder juude ma mi halfini",
];

List<String> titlesFr = [
  'Vous, qui sur la terre habitez',
  'Les cieux, en chaque lieu...',
  'Dieu me conduit',
  'Comme un cerf altéré brâme',
  'Miséricorde et grâce',
  "Peuples, venez, et qu'on entende...",
  'Que Dieu se montre seulement',
  "L'âme de douleur atteinte",
  'Tu fus toujours, Seigneur',
  'Bénissons Dieu...',
  'Heureux celui qui, par un juste choix',
  'Oui, je bénirai Dieu',
  'Je lève les yeux...',
  'Peuples, louez le grand Dieu',
  'Il faut, grand Dieu...',
  'Ô Père...',
  'Il a parlé, ce Dieu ...',
  'Dieu fort et grand!',
  'Du rocher de Jacob...',
  'Grand Dieu, nous te louons',
  'Ô toi dont les bienfaits',
  'Qui dit au soleil...',
  'Seigneur, à ton regard...',
  'Alléluia! Louange à Dieu!',
  "Gloire, gloire à l'Éternel!",
  'Gloire à toi, Dieu puissant!',
  'Adorons le Roi',
  "L'Éternel est ma part",
  'Grand Dieu puissant...',
  'Je chanterai, Seigneur...',
  'Jéhovah! Jéhovah!',
  'Grand Dieu! nous te bénissons',
  "Louez le nom de l'Éternel",
  'Mon âme exaltons la gloire',
  'Que ne puis-je, ô mon Dieu',
  'Trois fois saint Jéhovah!',
  'Peuples, chantez un saint cantique',
  'Abandonne ta vie',
  'Oui, ton amour...',
  "C'est de toi, Père saint...",
  'Gloire à toi, Dieu puissant!',
  'À toi la gloire!',
  'Je veux chanter...',
  'Ô Dieu! dans ses jours',
  "Oh! qu'il m'est doux...",
  'Oui, je veux te bénir',
  'Que ton fidèle amour',
  "Tu m'as aimé, Seigneur!",
  'Entendez-vous...',
  'Chantons, chantons sans cesse ...',
  'Hosanna! Béni soit...',
  'Lorsque le ciel retentit...',
  'Faisons éclater notre joie',
  'Ô charité suprême!',
  'Ô merveilleuse histoire',
  'Oh! que ne pouvons-nous...',
  'Divin Sauveur',
  'De la divinité...',
  'Saint envoyé du Père',
  "J'ai quitté le ciel pour toi",
  'Entonnons un saint cantique',
  'Ma richesse, ma gloire',
  'Ô bonne nouvelle!',
  "J'ai suivi Jésus",
  'Ô fils de Dieu',
  'Adorable mystère',
  "Je t'ai suivi sur le calvaire",
  'Pour moi, pécheur',
  "Sous ton voile d'ignominie",
  'Pour qui la mort',
  "O Christ ! j'ai vu ton agonie",
  'Pour nous, Christ meurt...',
  'Rédempteur adorable',
  'Sur cette terre',
  'Portant sa croix',
  'Un regard sur ta croix sanglante',
  'Il est la-bas, plus haut...',
  'Roi couvert de blessures',
  'À celui qui nous a sauvés',
  'Christ est ressuscité!',
  'À toi la gloire!',
  'Le Sauveur est ressuscité',
  'Venez, chrétiens',
  'Ô cieux! unissez-vous',
  'Jésus, agneau de Dieu!',
  'Ah! Si ton sang...',
  "Qu'elle est douce...",
  'Ô Seigneur!',
  'Oui, pour son peuple',
  "Tu m'as lavé de mon péché",
  'Tout mon bonheur, Christ...',
  'Comme un phare sur la plage',
  'Je la connais, cette joie...',
  'Seigneur Jésus!',
  'Je ne sais pourquoi...',
  'Je suis scellé pour la gloire',
  'Jésus est notre ami suprême',
  'Jésus, ô nom qui surpasse',
  "Mon Sauveur m'aime",
  'Lorsque dans ma souillure',
  "M'aimant...",
  "Ô Christ dont l'âme sympathise",
  "Redites-moi l'histoire",
  'Oh! parlez-moi',
  'Sauveur divin',
  'Vers toi, monte notre hommage',
  'Entendez-vous la dernière trompette',
  'Il va venir, le Seigneur',
  'Il vient, il vient...',
  'Levons-nous, frères',
  'Il va bientôt venir!',
  'Du ciel bientôt, Jésus va revenir',
  'Il revient sur la nuée',
  'Quel bonheur! Jésus vient!',
  'La trompette a retenti',
  'Il reviendra!',
  'Or, vers minuit...',
  'Prends courage, chrétien',
  'Seigneur Jésus! tes élus...',
  'Tenons nos lampes prêtes',
  'Écoutez le chant joyeux',
  'Esprit du Dieu vivant',
  'Descends, Esprit du Dieu vivant...',
  'Réponds à ma prière',
  'Ô Saint-Esprit',
  'Don du ciel',
  'Saint-Esprit',
  'Comme une terre altérée',
  'Esprit très saint',
  "Nous t'adorons, Dieu vivant",
  'Rends-toi maître...',
  'La Parole du Seigneur',
  "C'est dans ta Parole",
  'Livre saint',
  'Livre sacré, lumière étincelante...',
  'Pour triompher dans les combats',
  'Ta gloire, ô notre Dieu...',
  'Ta Parole, Seigneur',
  'Oh! Que ton joug est facile!',
  'O Seigneur...',
  'O Dieu de vérité',
  "L'Église est étrangère...",
  "C'est moi qui vous console",
  'Sur ton Église universelle',
  'Toi qui dans la nuit...',
  'Mon âme, en doux transports',
  'Aimer!',
  "Ah! Qu'il est beau...",
  'Fraternité céleste et sainte',
  'Il est en Jésus-Christ',
  "Nous t'adorons...",
  'Tu nous aimes, Seigneur!',
  'Que nos chants et nos prières',
  "L'amour de Jésus-Christ",
  'Ta voix, Jésus',
  'Ô Seigneur! ô Sauveur!',
  'Bénissons Dieu...',
  'Devant le Seigneur',
  'Frères, approchons-nous',
  'Marcher en ta présence...',
  'Immortel Roi des cieux',
  'Nous sommes au Seigneur',
  'Silence! Silence!',
  'Jour de repos...',
  'La semaine a fui',
  'Le jour a fui',
  'Monarque souverain',
  "Peuple chrétien, c'est le jour...",
  'Joyeusement, nous saluons...',
  'Repos si doux',
  'Quel bonheur, quand faisant trève',
  'Sur la terre se lève...',
  'Notre labeur est accompli',
  'Ton jour, Seigneur!',
  "L'astre à l'horizon descend",
  'Avec zèle à ton école...',
  'Mon âme en silence',
  'Ô Maître suprême!',
  'Ô chère école du sabbat',
  'À tes pieds, ô divin Maître!',
  'Repose ton âme',
  'Parle, parle Seigneur',
  'Daigne en cette heure...',
  'Divin Sauveur...',
  'Jésus te confie...',
  'Moment si doux de la prière',
  'Ô Dieu! toute ma prière',
  'Seigneur! du sein de la poussière...',
  'Quand le ciel devient menaçant',
  'Toi qui disposes',
  'Quelle est douce la prière',
  'Seigneur, ce que je réclame',
  'Souvent Seigneur!',
  'Au sortir de ton sanctuaire',
  'Demeure par ta grâce',
  'Ô Seigneur! Bénis la parole...',
  'Reste avec nous, Seigneur',
  "Que l'Éternel nous bénisse...",
  'Que la grâce de notre Seigneur...',
  'Dans le vaste champs du monde',
  'La voix de Christ nous appelle',
  'Passez jusques à nous!',
  'Frères, chantons...',
  "Des pays de l'aurore...",
  'Oui, la moisson du monde...',
  'Lève-toi, vaillante armée',
  "Qu'ils sont beaux...",
  "Semons dès que brille l'aurore",
  'Soleil de justice',
  'Seigneur Jésus!',
  'Viens, ô Jésus! régner...',
  'Annonçons partout...',
  "Cloches, sonnez l'Évangile",
  'Chantons la victoire',
  'Entends-tu le chant joyeux?',
  'Seigneur, ton ange vole',
  'Réjouis-toi, chrétien...',
  'Tel que je suis',
  'Contemplez, ô chrétiens!',
  'Je viens, Seigneur',
  'De ce monde...',
  'Mort avec Christ',
  'Seigneur Jésus...',
  'Tel que je suis sans rien à moi',
  'Viens à la croix',
  'Céleste voix, tu nous convies',
  'Agneau, victime expiatoire',
  'À ta Cène bénie',
  'Je viens, Seigneur, à ta table bénie...',
  'Roi des rois, victime sainte...',
  "Tu m'appelles, Seigneur",
  'Bientôt le Seigneur va venir!',
  'C\x92est encor temps',
  'Jésus frappe à votre porte',
  'Arrête, ô pécheur',
  "Entends-tu? Jésus t'appelle",
  "Pour toi, j'ai donné ma vie...",
  'Regarde, âme angoissée',
  "Lorsque devant l'agneau...",
  'Nous voguons vers un beau rivage',
  'Viens, âme perdue',
  'Le Maître est là qui t\x92appelle',
  "Ô vous qui n'avez pas la paix",
  'Où cherchez-vous le bonheur?',
  'Veux-tu partager la gloire',
  'Passant, si tard que veux-tu?',
  'Reviens à ton Père...',
  'Par ce chemin solitaire',
  'Pécheur, je voudrais te guérir',
  'Possèdes-tu, pauvre pécheur',
  'Pour nous la vie est un voyage',
  'Viens à Jésus',
  'Reviens!',
  'Une bonne nouvelle',
  'Si vous saviez...',
  'Toi dont l\x92âme est tourmentée',
  'Venez au Sauveur',
  'Viens à Jésus, quand la souffrance...',
  'Viens au Père',
  'Voici Jésus, notre Sauveur',
  'Nous allons tout joyeux...',
  'À ton appel, sur les flots',
  'Aujourd\x92hui tu m\x92appelles',
  'Chantez, anges du ciel!',
  'Dans ma misère',
  'Ô Seigneur',
  'Seigneur, tu donnes ta grâce',
  'Jésus, par ton sang précieux',
  'Ô Fils de Dieu, mon Sauveur',
  "J'ai trouvé la voie",
  'Miséricorde insondable',
  'Ô jour heureux',
  'Seigneur! je n\x92ai rien...',
  'Source féconde',
  "J'avais fui la bergerie",
  'Bien loin de toi, mon Père',
  "J'ai longtemps erré...",
  'Me voici devant ta face',
  'Ô  honte! ô mémoire cruelle!',
  'Père, je viens à toi',
  'Plongé dans un bourbier...',
  'Roc séculaire',
  'Sans attendre',
  'Seigneur, attire...',
  "C'est toi, Jésus",
  'Il est un nom si beau',
  'Exaltons notre divin Maître',
  'En quelque lieu...',
  'Roi des anges',
  'Dans les cieux',
  'Je connais un guide...',
  'Jésus, mon espérance',
  'Ô mon Sauveur!',
  'Doué du langage des anges...',
  'Je dois voyager...',
  'Quel autre au ciel...',
  "T'aimer, Jésus, te connaître...",
  'Frères, marchons!',
  'Jour après jour',
  'Vaillants soldats...',
  'La foi',
  'Le Dieu saint',
  'Que suis-je sur la terre?',
  'Brillante Étoile',
  'Ami, pourquoi tant de bonheur',
  'Comme un fleuve immense',
  'En toi, Seigneur',
  'Éternel Dieu, mon Sauveur',
  'La Croix que Dieu me donne',
  'Mon bonheur vient de toi',
  "J'ai soif de paix",
  'Quand je passe...',
  'Mon Dieu, nos coeurs...',
  "Quand le ciel s'ouvre...",
  'Sauveur toujours fidèle...',
  'Mon coeur joyeux',
  'Oh! quel repos, quand le mal...',
  'Plus le mal est pressant...',
  'Près de Jésus',
  'Quel ami fidèle et tendre!',
  'Quel repos céleste',
  'Seul refuge de mon âme',
  'Source de tous les biens',
  'Sur toi, je me repose...',
  "À Jésus, je m'abandonne...",
  'Ah! Donne à mon âme',
  'Grandis en moi, Seigneur',
  'Je me tiendrai tout près...',
  'Ah! que je ne sois pas...',
  "À toi, mon Dieu, je m'abandonne",
  "Aussi longtemps qu'étranger...",
  'Je suis à toi',
  'Seigneur, sanctifie',
  "C'est mon joyeux service...",
  'Le cri de mon âme',
  'Jésus-Christ est ma sagesse',
  'Je veux, pécheur...',
  'Les gains, les honneurs...',
  'Mon Sauveur',
  'Viens! mon âme...',
  'Ô mon Sauveur!',
  "Qu'il fait bon à ton service",
  'Toujours avec Jésus!',
  'À moi, les coeurs braves!',
  'Plus que vainqueurs!',
  'À de nouveaux combats',
  'Debout, sainte cohorte',
  "Dès que l'aube dépose",
  "Dès que l'aube dépose",
  'Seigneur dirige tous mes pas...',
  'Debout! soldats du Christ',
  "Jusqu'à la mort!",
  'Le temps est court',
  'Le signal de la victoire',
  "L'heure du départ",
  'Mon Dieu! quelle guerre cruelle!',
  'Poursuivons notre course',
  "C'est un rempart",
  "J'ai soif de ta présence",
  'Dieu tout-puissant',
  "Dans l'abime de misères",
  'Quand mon coeur en sa détresse',
  'Sur toi, Sauveur',
  "Voici venir l'orage",
  'Trop souvent, je murmure...',
  'Veille au matin',
  'Dans le désert...',
  'Mon Dieu, plus près de toi',
  'En ce triste monde...',
  'Il est un roc séculaire',
  'Il est une source',
  'Invoque-moi!',
  'Jésus est celui qui nous aime',
  'Le ciel était voilé',
  'Maître, entends-tu la tempête?',
  'Le vent soufflait...',
  'Mon âme est dans la détresse',
  'Ô Jésus, mon Sauveur',
  'Ô jour béni!',
  'Ô toi, mon allégresse',
  'Où trouver une retraite',
  'Oui, selon ta promesse...',
  'Quel grand secours!',
  'Viens, âme qui pleures',
  'Quand sur la sombre route',
  'Qui me relève...',
  'Si je trouve grande ma croix',
  'Une nacelle en silence',
  'Céleste Canaan',
  'Au ciel est la maison du Père',
  'Avec allégresse!',
  'De Canaan, quand verrons-nous',
  'Vers le ciel',
  'Contempler mon Dieu',
  'Encor quelques jours sur la terre',
  'Sainte Sion',
  'Étranger sur la terre',
  "J'ai vu dans une apothéose...",
  'Je connais un pays...',
  'Je ne sais pas le jour',
  'La Nuit aura bientôt disparu',
  "L'aube naît, sourit et passe",
  'Marchons, frères, bon courage',
  'Matelots en voyage',
  'Monts et coteaux reverdissent',
  'Nous attendons le Sauveur glorieux!',
  'Pèlerin sur cette terre',
  'Plus haut que les hautes cimes',
  'Pour moi chrétien',
  'Qui sont ces gens ...',
  'Que ta lumière...',
  'Dès le matin, Seigneur',
  'Ô mon Dieu!  Je cherche ta face',
  "Pour moi l'aurore...",
  'Une voix dans mon coeur...',
  'Je viens, Seigneur',
  "J'aime l'heure où sur la terre...",
  'Le soleil vers son déclin',
  'La nuit répand ses voiles...',
  "Déjà l'étoile s'allume aux cieux",
  'Ô notre Dieu...',
  "Ainsi que d'une lyre",
  'Au seuil de chaque année',
  'Nos figitives années',
  'Ô Dieu, que cette année',
  'Ô Seigneur, Éternel!',
  "C'est de toi, Dieu puissant...",
  'Père saint, dont la clémence',
  'Sur ces époux, Père éternel',
  'Sur ces époux, Seigneur...',
  "Qu'elle est douce, l'harmonie!",
  'On est bien à la maison',
  "Ô toi qui t'es donné",
  "Quel bonheur d'être en famille",
  "Qu'il fait bon",
  'Travailleur, voici le soir',
  'Cloches, sonnez!',
  'Oh! pendant que pour eux',
  'Ô Pasteur éternel',
  'Un nouveau combattant',
  'À toi, Seigneur, en ce beau jour',
  'Ô jour heureux!',
  'Dans ce grand jour',
  'Toi dont les cieux des cieux...',
  "C'est l'heure, amis...",
  'Jésus soit avec vous',
  'Reverra-t-il cette terre chérie?',
  "Elle n'est plus",
  'Nous mourrons, mais pour renaître',
  'Douleur profonde',
  "Plus haut que l'azur des cieux",
  'Pourquoi reprendre',
  'Plus de pleurs...',
  'Malheureuse famille',
  "Gémissant sous l'esclavage",
  'La route est glissante',
  'Pauvre buveur!',
  'Père, ô bon Père',
  'Venez captifs',
  'Ah! sous ton rire...',
  "Aux jours d'angoisse",
  'Dès le printemps de ta vie',
  "Dans la joie et l'allégresse",
  "Entends l'écho de la voix",
  'Es-tu lassé...',
  'Laisse ta folie',
  'Regarde au chemin du Calvaire',
  'Maintes fois',
  "Mot que l'on aime entendre",
  'Pourquoi la tristesse',
  'Oh! viens à moi',
  'Sur le seuil',
  'Oh! qui soutiendra',
  'Pendant les jours de ta jeunesse',
  'Pourquoi donc attendre',
  'Quand tu sondes ta misère',
  'Que devient mon enfant',
  'Toi, qui dans la carrière',
  'Viens, viens à Jésus!',
  'Voici, je me tiens à la porte',
  'À toi ma vie!',
  'Au combat de la vie',
  'À toi mon Dieu, je me donne...',
  'Il faut que mon coeur chante!',
  'Ce que Jésus-Christ nous demande',
  'Des paroles de charmes',
  'Choisir Jésus dès la jeunesse',
  'Comme un enfant...',
  "Entre tes mains, j'abandonne",
  "Entendez-vous l'appel du Maître?",
  "Je m'approche de toi",
  'En ce monde de tristesse',
  'Mon coeur te cherche...',
  'Jésus, doux Maître',
  "La voix du Seigneur m'appelle",
  "J'entends ta douce voix",
  'Je suis à toi, mon Dieu...',
  'Jeunesse ardente',
  'Mon coeur tressaille à ta voix',
  'Jésus, je te suivrais partout',
  'Lève-toi, lève-toi...',
  "Oui, Jésus, c'est vers toi",
  'Ô toi qui donnes la vie',
  'Oh!  quel beau jour',
  'Tout joyeux, bénissons le Seigneur',
  'Prends ma vie...',
  'Sans Jésus, je ne peux vivre',
  'Seigneur, mon âme soupire',
  'Sois ma lumière',
  'Tiens dans ta main...',
  'Toujours ta divine présence',
  'Voir mon Sauveur face à face',
  'En Jésus je demeure',
  "C'est Jésus, quand je chancelle...",
  "C'est à l'ombre de tes ailes",
  'Quand sur ma tête...',
  'Je chanterai ton grand amour',
  "Je l'ai trouvé!",
  'Joie au ciel!',
  'Le nom de Jésus est si doux!',
  'Mortels, voulez-vous savoir',
  "Ne crains rien, je t'aime",
  'Oui, tout est bien',
  "Pour toi qu'un tourment oppresse",
  'Pour la céleste cité, dites-moi',
  'Quand écrasé...',
  'Quand le vol de la tempête ...',
  'Toute chaîne est enlevée',
  'Debout pour la sainte guerre!',
  'Debout, volontaires!',
  "Écoutez l'appel du berger!",
  "Entends-tu l'appel du Maître?",
  'La voix de tes sentinelles',
  'Messagers du grand Roi',
  'Seigneur, que la terre entière',
  'Sentinelle vigilante',
  'Revêts tes armes, volontaire!',
  'Travaillons et luttons!',
  'Travaillons tous pour notre Maître',
  'Lorsque Dieu nous appelle',
  'Volontaires, au combat!',
  "À toi nos transports d'allégresse",
  'Amis, chantons ensemble',
  'À toi, Seigneur, nos saints transports',
  "Dans l'ombre et le silence",
  'Il faut cueillir les fleurs!',
  'Le jour paraît, et la nature',
  'Le laboureur retourne...',
  "Qu'elle est pure et belle",
  "J'aime du soir les pures harmonies",
  'Jésus! Jésus!',
  "À l'Éternel qu'on chante",
  'Bon Sauveur, Berger fidèle',
  'As-tu compté...',
  "Cherchons dès l'enfance",
  'Chaque jour de ma vie',
  'Enfants, soyez sages',
  'Deux mains pour servir',
  "Dans l'eau fraîche et limpide",
  'Jésus est au milieu de nous',
  'Je suis la lumière',
  "J'aime à penser...",
  'Je suis petit',
  'Le Seigneur Jésus...',
  "Le Seigneur m'aime",
  'Me voici, jeune ouvrier',
  "David n'avait rien que sa fronde",
  'Mon bon Sauveur',
  "Mon Sauveur, c'est par la foi",
  'La bande joyeuse',
  'Mon Sauveur, je voudrais être...',
  "Nul enfant n'est trop petit...",
  'Pour le bon Dieu...',
  "Tant qu'il vit",
  'Pour le Seigneur...',
  'Pour chanter les louanges',
  'Que je sois...',
  'Seigneur que faut-il que je fasse',
  'Toi qui veux être notre frère',
  'À ton école',
  'Douce cloche, chante...',
  "Entrons à l'école",
  "Sortons de l'école",
  'Seigneur, de ta demeure',
  'Tinte, pièce blanche!',
  'Oh! que ta main paternelle',
  "L'ombre étend ses voiles",
  "Si du nid tombe l'oisillon",
  "L'ombre descend de la colline",
  'Réveillez-vous fleurettes',
  "Palais d'ivoire",
  'Connais-tu cette cité',
  "Dans le jardin où j'aime entrer",
  'Au séjour des bienheureux',
  'Entends la voix du Sauveur ...',
  'Flots mugissants...',
  'Le Fils de Dieu...',
  'Il faisait nuit...',
  'Meurs! ô Jésus...',
  "Le ciel pâlit à l'orient",
  'Mon Dieu, plus près de toi',
  'Tu payas mon salut...',
  'Seigneur, que n\x92ai-je mille voix!',
  "Je m'approche de toi...",
  "Louez l'Éternel en tous lieux",
  'Gloire à mon Dieu!',
  "Jésus m'entend...",
  'On frappe...',
  "Seigneur, mon Dieu, je t'adore...",
  'Je veux pécheur...',
  'Sur mon chemin...',
  'Dieu, mon péché me désole!',
  'Le Colporteur Vaudois',
  'Dans Sion, pays de gloire',
  'Ô toi, source intarissable',
  'Nuit sans espoir',
  "L'Éternel seul est Seigneur",
  'Christ est mon rocher',
  'Chrétiens, voici le Rédempteur!',
  'Vous qui pleurez, venez',
  'Christ va venir',
  'Confiance',
  'Enfants de lumière',
  'Merci, Seigneur...',
  'Les cieux en coeur',
  'Voyez, voyez quel amour...',
  'Pluviôse',
  'La Pâque',
  'Ô Dieu puissant',
  'Jérusalem, cité de Dieu',
  'Jérusalem, cité des cieux',
  'Ô notre Père',
  'Sur tes murs...',
  'À Celui qui sied sur le trône',
  'Salut, montagnes bien-aimées!',
  "Qu'il est beau, mon pays!",
  'Sur nos monts',
  'Je veux répondre, ô Dieu!',
  'À toi, Seigneur, à toi seul...',
  'Au sein de la nuit...',
  'À toi ma vie, à toi mon coeur',
  'Gloire au grand Dieu!',
  'Ce jour est au Seigneur!',
  'Debout! debout!',
  'Je te suivrai...',
  'Invocation',
  'Le Seigneur nous appelle',
  'Levons-nous',
  'Suivons...',
  'Il est là-bas...',
  'Saint des saints...',
  'Quand la nuit étend son voile',
  'Chant du soir',
  'Nuit bénie'
];
List<String> titlesEn = [
  'Praise to the Lord',
  'All creatures of our God and King',
  'God Himself Is With Us',
  'Praise, My Soul, the King of Heaven',
  'All My Hope on God Is Founded',
  'O Worship the Lord',
  'The Lord in Zion Reigneth',
  'We Gather Together',
  'Let All the World in Every Corner Sing',
  'Come, Christians, Join to Sing',
  'The God of Abraham Praise',
  'Joyful, Joyful, We Adore Thee',
  'New Songs of Celebration Render',
  'Let Us Praise the Name of the Lord',
  'My Maker and My King',
  'All People That on Earth Do Well',
  'Lord of All Being, Throned Afar',
  'O Morning Star, How Fair and Bright',
  'O Sing a New Song to the Lord',
  '20 O Praise Ye the Lord',
  'Immortal, Invisible, God Only Wise',
  'God Is Our Song',
  'Now the Joyful Bells A-Ringing',
  'Every Star Shall Sing a Carol',
  'Praise the Lord, His Glories Show',
  'Praise the Lord! You Heavens Adore Him',
  'Rejoice, Ye Pure in Heart!',
  'Praise We the Lord',
  'Sing Praise to God',
  'Holy God, We Praise Your Name',
  'Tell Out, My Soul',
  'When in Our Music God is Glorified',
  'Sing a New Song to the Lord',
  'Wake the Song',
  'With Songs and Honors',
  'O Thou in Whose Presence',
  'O Sing, My Soul, Your Maker`s Praise',
  'Arise, My Soul, Arise!',
  'Lord, in the Morning',
  'The Dawn of God`s Dear Sabbath',
  'O Splendor of God`s Glory Bright',
  'Now That the Daylight Fills the Sky',
  'When Morning Gilds the Skies',
  'Morning Has Broken',
  'Open Now Thy Gates of Beauty',
  'Abide With Me, `Tis Eventide',
  'God, Who Made the Earth and Heaven',
  'Softly Now the Light of Day',
  'Savior, Breathe an Evening Blessing',
  'Abide With Me',
  'Day Is Dying in the West',
  'Now the Day Is Over',
  'All Praise to Thee',
  'O Gladsome Light',
  'Jesus, Tender Shepherd, Hear Me',
  'The Day Thou Gavest',
  'Now All the Woods Are Sleeping',
  'Hark, the Vesper Hymn Is Stealing',
  'Great Our Joy as Now We Gather',
  'Blessed Jesus at Thy Word',
  'God Is Here!',
  'How Lovely Is Thy Dwelling Place',
  'O Come, Let Us Sing to the Lord',
  'Lord, Dismiss Us With Thy Blessing',
  'God Be With You',
  'God Be With You',
  'O Lord, Now Let Your Servant',
  'On Our Way Rejoicing',
  'Lord, Make Us More Holy',
  'Praise Ye the Father',
  'Come Thou Almighty King',
  'Creator of the Stars of Night',
  'Holy, Holy, Holy',
  'Like a River Glorious',
  'The Wonder of It All',
  'O Love That Wilt Not Let Me Go',
  'O Love of God Most Full',
  'For God So Loved Us',
  'O Love of God, How Strong and True!',
  'O World of God',
  'Though I Speak With Tongues',
  'Before Jehova`s Awful Throne',
  'O Worship the King',
  'God the Omnipotent',
  'Eternal Father, Strong to Save',
  'How Great Thou Art',
  'God Who Spoke in the Beginning',
  'I Sing the Migthy Power of God',
  'Let All on Earth Their Voices Raise',
  'Eternal God, Whose Power Upholds',
  'Ye Watchers and Ye Holy Ones',
  'This Is My Father`s World',
  'All Things Bright and Beautiful',
  'Nature With Open Volume Stands',
  'Spring Has Now Unwrapped the Flowers',
  'The Spacious Firmament',
  'Lord of the Boundless Curves of Space',
  'Can You Count the Stars?',
  'God Will Take Care of You',
  'Great Is Thy Faithfulness',
  'Children of the Heavenly Father',
  'Unto the Hills',
  'O God, Our Help in Ages Past',
  'My Shepherd Will Supply My Need',
  'Sing to the Great Jehovah`s Praise',
  'Give to Our god Immortal Praise',
  'God Moves in a Mysterious Way',
  'Amazing Grace',
  'Marvelous Grace',
  'God`s Free Mercy Streameth',
  'It Took a Miracle',
  'Let Us With a Gladsome Mind',
  'As Pants the Hart',
  'There`s a Wideness',
  'O Come, O Come, Immanuel',
  'Of the Father`s Love Begotten',
  'The Advent of Our God',
  'The First Noel',
  'Angels From the Realms of Glory',
  'There`s a Song in the Air',
  'Go, Tell It On the Mountain',
  'Hark! the Herald Angels Sing',
  'As With Gladness Men of Old',
  'Away in a Manger',
  'Joy to the World',
  'In the Bleak Midwinter',
  'Infant Holy, Infant Lowly',
  'Break Forth, O Beauteous Heavenly Light',
  'As It Fell Upon a Night',
  'It Came Upon the Midnight Clear',
  'Lo, How a Rose E`er Blooming',
  'O Come, All Ye Faithful',
  'Now Is Born the Divine Christ Child',
  'O Jesus Sweet',
  'O Little Town of Bethlehem',
  'Good Christians, Now Rejoice',
  'We Three Kings',
  'Rise Up, Shepherd, and Follow',
  'While Shepherds Watched Their Flocks',
  'Thou Didst Leave Thy Throne',
  'What Child Is This?',
  'Angels We Have Heard on High',
  'Silent Night, Holy Night',
  'O Sing a Song of Bethlehem',
  'Songs of Thankfulness and Praise',
  'I Think When I Read That Sweet Story',
  'Christ Upon the Mountain Peak',
  'O Love, How Deep, How Broad',
  'Once in Royal David`s City',
  'Who Is He in Yonder Stall?',
  'Jesus Walked This Lonesome Valley',
  'Tell Me the Story of Jesus',
  'Prince of Peace, Control My Will',
  'When I Survey the Wondrous Cross',
  'When I Survey the Wondrous Cross',
  'O Sacred Head Now Wounded',
  'Go to Dark Gethsemane',
  'Were You There?',
  'The Old Rugged Cross',
  'Ride On in Majesty',
  'Throned Upon the Awful Tree',
  'Wondrous Love',
  'At the Cross',
  'There Is a Green Hill Far Away',
  'Look, You Saints! the Sight Is Glorious',
  'Christ the Lord Is Risen Today',
  'Alleluia! Sing to Jesus!',
  'And Have the Bright Immensities',
  'Come, You Faithful',
  'Come, You Faithful',
  'Thine Is the Glory',
  'The Strife Is O`er',
  'Good Christian Friends, Rejoice!',
  'Star of Our Hope',
  'Now the Green Blade Rises',
  'Hail the Day That Sees Him Rise',
  'Jesus, Your Blood and Righteousness',
  'The Unveiled Christ',
  'The Wonders of Redeeming Love',
  'O Listen to Our Wondrous Story',
  'Does Jesus Care?',
  'Christ Is Alive',
  'I Will Sing of Jesus` Love',
  'Jesus Paid It All',
  'Jesus Is All the World to Me',
  'I`ve Found a Friend',
  'Jesus, What a Friend for Sinners',
  'My Song Is Love Unknown',
  'All That Thrills My Soul',
  'Jesus Loves Me',
  'Love Divine',
  'All That Thrills My Soul',
  'Savior, Teach Me',
  'Sing We of the Modern City',
  'Showers of Blessing',
  'Tell Me the Old, Old Story',
  'The King of Love My Shepherd Is',
  'And Can It Be?',
  'The Head That Once Was Crowned',
  'The Lord Is Coming',
  'Christ Is Coming',
  'Hail Him the King of Glory',
  'This Is the Threefold Truth',
  'Come, Thou Long Expected Jesus',
  'Gleams of the Golden Morning',
  'Face to Face',
  'It May Be at Morn',
  'There`ll Be No Dark Valley',
  'That Glorious Day Is Coming',
  'Wake, Awake for the Night Is Flying',
  'Lo! He Comes',
  '`Tis Almost Time for the Lord to Come',
  'Jesus Is Coming Again',
  'We Have This Hope',
  'The King Shall Come',
  'When the Roll Is Called Up Yonder',
  'The Church Has Waited Long',
  'When He Cometh',
  'When Jesus Comes in Glory',
  'When He Comes',
  'Rejoice, the Lord Is King',
  'Hark! Ten Thousand Harps and Voices',
  'Crown Him With Many Crowns',
  'Seek Ye First the Kingdom',
  'God Is Working His Purpose Out',
  'Lift Up Your Heads',
  'Jesus Shall Reign',
  'A Hymn of Glory Let Us Sing',
  'All Hail the Power of Jesus` Name',
  'All Glory, Laud, and Honor',
  'Blest Be the King',
  'At the Name of Jesus',
  'Christ, Whose Glory Fills the Skies',
  'Christ Is the World`s Light',
  'Christ Is Made the Sure Foundation',
  'I Love Thee',
  'In the Cross of Christ I Glory',
  'How Sweet the Name!',
  'Jesus, Priceless Treasure',
  'Fairest Lord Jesus',
  'Jesus, the Very Thought of Thee',
  'Jesus, Thou Joy of Loving Hearts',
  'King of Glory, King of Peace',
  'My Song Shall Be of Jesus',
  'More About Jesus',
  'Worthy, Worthy Is the Lamb',
  'Come, My Way',
  'O, How I Love Jesus',
  'Praise Him! Praise Him!',
  'O for a Thousand Tongues to Sing',
  'He Lives',
  'Come, Let Us Sing',
  'There`s No Other Name Like Jesus',
  'The Great Physician Now is Near',
  'I Cannot Tell Why',
  'Ye Servants of God',
  'Come Down, O Love Divine',
  'Baptize Us Anew',
  'Draw Us in the Spirit`s Tether',
  'Hover O`er Me, Holy Spirit',
  'The Spirit of the Lord Revealed',
  'Sweet, Sweet Spirit',
  'Fire of God, Thou Sacred Flame',
  'O for That Flame of Living Fire',
  'Breathe on Me, Breath of God',
  'Spirit of God',
  'Spirit Divine',
  'Holy Spirit, Light Divine',
  'Come, Holy Spirit',
  'O Holy Dove of God Descending',
  'Break Thou the Bread of Life',
  'Give Me the Bible',
  'Lord, I Have Made Thy Word My Choice',
  'O Word of God Incarnate',
  'O God of Light',
  'Thanks to God',
  'For Your Holy Book We Thank You',
  'Lord Jesus, Once You Spoke to Men',
  'Only Trust Him',
  'Come, Ye Sinners',
  'I Gave My Life for Thee',
  'I Hear Thy Welcome Voice',
  'O Jesus, Thou Art Standing',
  'For You I Am Praying',
  'Jesus Calls Us',
  'Wonderful Words of Life',
  'Softly and Tenderly',
  'I Am Going to Calvary',
  'The Savior Is Waiting',
  'Turn Your Eyes Upon Jesus',
  'We Have Not Known Thee',
  'Jesus, I Come',
  'Heavenly Father, Bless Us Now',
  'Power in the Blood',
  'Chief of Sinners',
  'Lord, I`m Coming Home',
  'God Be Merciful to Me',
  'I Lay My Sins on Jesus',
  'Forgive Our Sins as We Forgive',
  'Rock of Ages',
  'Near, Still Nearer',
  'Deeper Yet',
  'Beneath the Cross of Jesus',
  'Faith of Our Fathers',
  'Give Me Jesus',
  'Draw Me Nearer',
  'I Am Coming to the Cross',
  'Wholly Thine',
  'I Surrender All',
  'I Would Draw Nearer to Jesus',
  'I Would Be Like Jesus',
  'Near the Cross',
  'Just as I Am',
  'Just as I Am',
  'O for a Closer Walk!',
  'Live Out Thy Life Within Me',
  'Lead Me to Calvary',
  'Whiter Than Snow',
  'Lord, I Want to Be a Christian',
  'Lord of Creation',
  'My Jesus, I Love Thee',
  'Nothing Between',
  'O for a Heart to Praise My God!',
  'Just as I Am, Thine Own to Be',
  'Jesus, I My Cross Have Taken',
  'Open My Eyes That I May See',
  'I`d Rather Have Jesus',
  'Must Jesus Bear the Cross Alone',
  'Take the World, but Give Me Jesus',
  'Take My Life and Let It Be',
  'O Jesus, I Have Promised',
  'The Cleansing Wave',
  'On Jordan`s Banks the Baptist`s Cry',
  'Come, Thou Fount of Every Blessing',
  'What a Wonderful Savior',
  'There Is a Fountain',
  'Redeemed!',
  'Redeemed!',
  'God Is My Strong Salvation',
  'Jesus Saves',
  'To God Be the Glory',
  'Is This a Day of New Beginnings?',
  'I Will Sing of My Redeemer',
  'I Love Your Kingdom, Lord',
  'Christ Is the World`s True Light',
  'Lord, Who Dost Give to Thy Church',
  'Built on the Rock',
  'The Church Has One Foundation',
  'God is Love',
  'Blest Be the Tie That Binds',
  'Thy Hand, O God Has Guided',
  'This Is My Will',
  'Father, Help Your People',
  'Thy Love, O God',
  'Where Cross the Crowded Ways of Life',
  'All Who Love and Serve Your City',
  'Come, Labor On',
  'Far and Near the Fields Are Teeming',
  'Hark! the Voice of Jesus Calling',
  'From the Eastern Mountains',
  'Hark! `Tis the Shepherd`s Voice I Hear',
  'Lift High the Cross',
  'Lord, Whose Love in Humble Service',
  'O Jesus Christ, to You',
  'O Zion, Haste',
  'O Where Are the Reapers?',
  'Rescue the Perishing',
  'Watchman, Blow the Gospel Trumpet',
  'Bringing in the Sheaves',
  'Christ for the World',
  'Lift Him Up',
  'How Beauteous Are Their Feet',
  'Seeking the Lost',
  'Jesus, With Thy Church Abide',
  'Work, for the Night Is Coming',
  'All Things Are Thine',
  'Go Forth, Go Forth With Christ',
  'Go, Preach My Gospel',
  'We Give This Child to You',
  'Welcome, Day of Sweet Repose',
  'Holy Sabbath Day of Rest',
  'O Day of Rest and Gladness',
  'O Day of Rest and Gladness',
  'Safely Through Another Week',
  'Crowning Jewel of Creation',
  'The Sacred Anthem',
  'Come, O Sabbath Day',
  'Don`t Forget the Sabbath',
  'Light of Light, Enlighten Me',
  'We Love Thy Sabbath, Lord',
  'Welcome, Welcome, Day of Rest',
  'Dear Lord, We Come at Set of Sun',
  'Lord of the Sabbath',
  'Far From All Care',
  'As Birds Unto the Genial Homeland',
  'Lord God, Your Love Has Called Us Here',
  'An Upper Room',
  'Bread of the World',
  'Beneath the Forms of Outward Rite',
  'I Come With Joy',
  'In Imitation, Lord of Thee',
  'By Christ Redeemed',
  'Let Us Break Bread Together',
  'Now Let Us From This Table Rise',
  'O God, Unseen, Yet Ever Near',
  'Love Consecrates the Humblest Act',
  'Sent Forth by God`s Blessing',
  'Lord, Enthroned in Heavenly Splendor',
  'Jesus Invites His Saints',
  'Thy Broken Body, Gracious Lord',
  'The Son of God Proclaim',
  'Cover With His Life',
  'God Has Spoken by His Prophets',
  'Fruitful Trees, the Spirit`s Sowing',
  'Christ the Lord, All Power Possessing',
  'The Judgment Has Set',
  'O Solemn Thought',
  'Day of Judgment, Day of Wonders!',
  'Soon Shall the Trump of God',
  'Jerusalem, My Happy Home',
  'For All the Saints',
  'Marching to Zion',
  'Glorious Things of Thee Are Spoken',
  'For Thee, O Dear, Dear Country',
  'Holy, Holy, Is What the Angels Sing',
  'I Shall See the King',
  'No Night There',
  'Sweet By and By',
  'Jerusalem the Golden',
  'Joy By and By',
  'Over Yonder',
  'Shall We Gather at the River',
  'Ten Thousand Times Ten Thousand',
  'We Speak of the Realms',
  'The Glory Song',
  'The Homeland',
  'I`m Going Home',
  'You Will See Your Lord A-Coming',
  'How Far From Home?',
  'How Cheering Is the Christian`s Hope',
  'I Saw One Weary',
  'How Sweet Are the Tidings',
  'There`ll Be No Sorrow There',
  'I`m a Pilgrim',
  'I`m But a Stranger Here',
  'Lo, What a Glorious Sight Appears',
  'Long Upon the Mountains',
  'O, When Shall I See Jesus',
  'Never Part Again',
  'Beautiful Zion',
  'Together Let Us Sweetly Live',
  'What Heavenly Music',
  'We Have Heard',
  'Don`t You See My Jesus Coming',
  'Immortal Love, Forever Full',
  'My Lord and I',
  'I Love to Tell the Story',
  'More Love to Thee',
  'As the Bridegroom to His Chosen',
  'As Water to the Thirsty',
  'Be Still, My Soul',
  'Blessed Assurance, Jesus is Mine!',
  'Peace, Perfect Peace',
  'When I Can Read My Title Clear',
  'I Heard the Voice of Jesus',
  'Wonderful Peace',
  'Life Is Great! So Sing About It',
  'A Child of the King',
  'Leaning on the Everlasting Arms',
  'There`s Sunshine in My Soul Today',
  'Grant Us Your Peace',
  'A Song of Heaven and Homeland',
  'Nearer My God, to Thee',
  'Take the Name of Jesus With You',
  'Balm in Gilead',
  'Burdens Are Lifted at Calvary',
  'Come, Ye Disconsolate',
  'Sweet Hour of Prayer',
  'Tread Softly',
  'Dear Lord and Father',
  'Dear Lord and Father',
  'Father, Lead Me Day by Day',
  'I Need Thee Every Hour',
  'I Need Thee, Precious Jesus',
  'I Must Tell Jesus',
  'I Do Believe',
  'In the Garden',
  'At First I Prayed for Light',
  'Jesus, Lover of My Soul',
  'Jesus, Lover of My Soul',
  'In the Hour of Trial',
  'Like Jesus',
  'Fill My Cup, Lord',
  'We Would See Jesus',
  'Near to the Heart of God',
  'Eternal Love, We Have No Good',
  'O Gracious Father of Mankind',
  'Still, Still With Thee',
  'What a Friend We Have in Jesus',
  'Take Time to Be Holy',
  'Tis the Blessed Hour of Prayer',
  'Sun of My Soul',
  'A Quiet Place',
  'Lord Jesus, Think on Me',
  'I Need the Prayers',
  'A Mighty Fortress',
  'Moment by Moment',
  'Anywhere With Jesus',
  'How Firm a Foundation',
  'If You But Trust in God to Guide You',
  'I Know Whom I Have Believed',
  'Just When I Need Him Most',
  'In Heavenly Love Abiding',
  'Lord of Our Life',
  'The Lord Is My Light',
  'All the Way',
  'My Faith Looks Up to Thee',
  'Standing on the Promises',
  'Give to the Winds Your Fears',
  'He Hideth My Soul',
  'Depth of Mercy',
  'My Hope Is Built on Nothing Less',
  'My Faith Has Found a Resting Place',
  'Tis So Sweet to Trust in Jesus',
  'Hiding in Thee',
  'Because He Lives',
  'From Every Stormy Wind',
  'A Shelter in the Time of Storm',
  'Under His Wings',
  'It Is Well With My Soul',
  'We`ll Build on the Rock',
  'Day by Day',
  'O for a Faith',
  'Will Your Anchor Hold',
  'I Am Trusting Thee, Lord Jesus',
  'God, Who Stretched',
  'He Leadeth Me',
  'Guide Me, O Thou Great Jehovah',
  'I Will Early Seek the Savior',
  'Gentle Jesus, Meek and Mild',
  'Lord, Speak to Me',
  'Jesus, Friend So Kind',
  'Jesus, Friend of Little Children',
  'Jesus, Son of Blessed Mary',
  'Savior, Like a Shepherd',
  'The Lord`s My Shepherd',
  'Be Thou My Vision',
  'Now Praise the Hidden God of Love',
  'Loving Shepherd of Thy Sheep',
  'Every Flower That Grows',
  'Jesus, Savior, Pilot Me',
  'The Lord`s My Shepherd',
  'Jesus, Guide Our Way',
  'O Let Me Walk With Thee',
  'Shepherd of Tender Youth',
  'As Saints of Old',
  'Come, Ye Thankful People',
  'For the Fruits of His Creation',
  'Now Thank We All Our God',
  'Let All Things Now Living',
  'We Plow the Fields',
  'Come, Sing a Song of Harvest',
  'Praise and Thanksgiving',
  'For Sunrise Hope and Sunset Calm',
  'For the Beauty of the Earth',
  'Father, We Thank You',
  'Have Thine Own Way, Lord',
  'Make Me a Captive, Lord',
  'Pass Me Not, O Gentle Savior',
  'Not I, But Christ',
  'What Does the Lord Require?',
  'Give of Your Best to the Master',
  'I`ll Go Where You Want Me to Go',
  'O Master, Let Me Walk With Thee',
  'Let Your Heart Be Broken',
  'Awake, Awake to Love and Work',
  'In the Heart of Jesus',
  'So Send I You',
  '`Tis Love That Makes Us Happy',
  'This Little Light of Mine',
  'When the Church of Jesus',
  'Working, O Christ, With Thee',
  'You That Know the Lord',
  'There`s a Spirit in the Air',
  'When Christ Was Lifted From the Earth',
  'What Joy It Is to Worship Here',
  'In Christ There Is No East nor West',
  'Lord of All Nations',
  'Holy Spirit, Gracious Guest',
  'Trust and Obey',
  'In Our Work and in Our Play',
  'Watchman, Tell Us of the Night',
  'In Times Like These',
  'Heir of the Kingdom',
  'Let Every Lamp Be Burning',
  'Look for the Waymarks',
  'Ye Servants of the Lord',
  'Watch, Ye Saints',
  'Rejoice, Rejoice, Believers',
  'Hold Fast Till I Come',
  'Watchmen, on the Walls of Zion',
  'O Brother, Be Faithful',
  'Christian, Seek Not Repose',
  'We Know Not the Hour',
  'My Soul, Be on Thy Guard',
  'Once to Every Man and Nation',
  'God of Grace and God of Glory',
  'Faith Is the Victory',
  'Am I a Soldier of the Cross?',
  'Stand Like the Brave',
  'Awake, My Soul!',
  'Onward, Christian Soldiers!',
  'Fight the Good Fight',
  'Sound the Battle Cry',
  'Rise Up, O Church of God',
  'Soldiers of Christ, Arise',
  'We Are Living, We Are Dwelling',
  'Stand Up! Stand Up for Jesus!',
  'Lead On, O King Eternal',
  'On Jordan`s Stormy Banks',
  'Gracious Father, Guard Thy Children',
  'Come, Come, Ye Saints',
  'I Will Follow Thee',
  'I Want Jesus to Walk With Me',
  'Higher Ground',
  'In a Little While We`re Going Home',
  'Jacob`s Ladder',
  'As Jacob With Travel Was Weary',
  'O Happy Band of Pilgrims',
  'Rise, My Soul, and Stretch Thy Wings',
  'When on Life a Darkness Falls',
  'Until Then',
  'When We All Get to Heaven',
  'Come, All Christians, Be Committed',
  'Lord of All Good',
  'God, Whose Giving Knows No Ending',
  'Son of God, Eternal Savior',
  'The Wise May Bring Their Learning',
  'A Diligent and Grateful Heart',
  'For Beauty of Meadows',
  'God in His Love for Us',
  'We Praise Thee With Our Minds',
  'Father, Who on Us Do Shower',
  'O God, Whose Will Is Life and Good',
  'God of our fathers',
  'To the Name That Brings Salvation',
  'Mine Eyes Have Seen the Glory',
  'I Vow to Thee, My Country',
  'Lord, While for All Mankind We Pray',
  'Our Father, by Whose Name',
  'Happy the Home That Welcomes You',
  'Love at Home',
  'Lead Them, My God, to Thee',
  'Lord, Bless Our Homes',
  'Happy the Home',
  'O Perfect Love',
  'O God, From Whom Mankind',
  'Heavenly Father, Hear Our Prayer',
  'May the Grace of Christ Our Savior',
  'Glory Be to the Father',
  'Holy, Holy, Holy',
  'Let All Mortal Flesh Keep Silence',
  'Amens',
  'Sevenfold Amen',
  'All Things Come of Thee',
  'Cast Thy Burden Upon the Lord',
  'Lord, Bless Thy Word to Every Heart',
  'O Thou Who Hearest',
  'The Lord Bless You and Keep You',
  'We Give Thee But Thine Own',
  'Now, Dear Lord, As We Pray',
  'Spirit of the Living God',
  'May God Be With You',
  'Shalom',
  'May the Lord Bless and Keep You',
  'Thy Word Is a Lantern',
  'Heavenly Father, to Thee We Pray',
  'God Be in My Head',
  'God Be in My Head',
  'Holy Spirit, Hear Us',
  'This Is the Day the Lord Hath Made',
  'As You Have Promised, Lord',
  'Jesus, Stand Among Us',
  'Hear Our Prayer, O Lord',
  'Cause Me to Hear',
  'Bless Thou the Gifts',
  'The Lord Is in His Holy Temple',
  'Surely, Surely',
  'Day by Day, Dear Lord',
  'Dismiss Us, Lord, With Blessing',
  'Lead Me, Lord',
  'The Lord Is in His Holy Temple',
  'Almighty Father',
  'Praise God, From Whom All Blessings',
  'Praise God, From Whom All Blessings'
];
