final List<String> cantiquesFulfulde = [
  "Yesu yidi bikkon fu",
  "Dum seyo tokkago lawol",
  "Jodago ha kosde yesu",
  "Sobabe ngurte ha nder nyibre",
  "Baba cenido",
  "Mi don teddina ma allah",
  "Yesu krist don wanca be am",
  "Wodi sobajo am yesu",
  "Yeesu mayi ha gafingal",
  "Nda lekkita manga wari",
  "Baba mi yidi ma",
  "Bana mi woni aybejo",
  "wala sobajo buran yeesu",
  "Mi yidi yalade sabba",
  "Yeesu krist badita hande",
  "Sondu ha ladde",
  "Gafingal yeesu krist",
  "Duniyaru ndu mere",
  "Baddi be yeesu krist",
  "Labinol bernde",
  "War ha yeesu",
  "Baba am don yila be am",
  "Wodi lesdi ha allahhira",
  "Boyma mi anda kisnowo",
  "Gafingal yeesu",
  "Yeesu kisnowo kibuudo",
  "Minin ngidi dowtare",
  "Biddo allah",
  "Yeesu yidi yam",
  "Jodu be am",
  "Tapare duminde",
  "Yeesu badi wartugo",
  "Ha nder asaman",
  "Burdum ha yeesu",
  "Yeesu kisnowo yam",
  "Teddingo allah",
  "Ummatore yimbe allah",
  "Yeesu gainako boddo",
  "Timminol sodol",
  "Mobture hisnabe",
  "Allah jodida be ma",
  "Hubar mbelka",
  "Be siru",
  "Hakke am hosama gal kisnowo",
  "Yeesu be kisnowo",
  "Yimre nyalade sabbat",
  "Ngade zakka",
  "Endam yajaumirawo yeesu-krist",
  "Ruuhu cenido",
  "Berniwol seningol ha asaman",
  "Wartol yeesu nder wudare",
  "Zunubajo bana mi wa'i",
  "Boddumji don har ma ",
  "Jodibe ha lesdi fu",
  "Deftere allah lati jayngol",
  "Allah ewni ma ",
  "Gaynako boddo ",
  "Tokken lawol be gorgaku ",
  "To wodi yide ha sare  ",
  "Yeesu, mi tokkete toye fu",
  "Min ngari ha sudu mada ",
  "Mi yetti ngam yide baba be yeesu ",
  "Moye hisnata duniyaru  ",
  "Kugal mada lati bodngal ",
  "Yeesu jodan cakka meden",
  "Hokku en ruhu mada",
  "Sukka ma wari ",
  "Wi'i fu ha yeesu",
  "Tokkago lawol gongaku",
  "Baba jogam",
  "Sembe don nder yiam yeesu",
  "Ya jawmirawo mi yenwi ma",
  "Mi woni jayngol ma",
  "Lawol kisndam",
  "Ngam ma mi wadi dum",
  "War ha baba hande",
  "Endam kisnowo yam",
  "Ha dukki wade min latan aman'en",
  "Sanya pukarajo",
  "Mi don tefa jam be endam",
  "Mi don be mada",
  "Zunubajo mi hurgete",
  "Sawtu yeesu don noddi yam",
  "Barka kisnowo yeesu-krist",
  "Nyalade fu nder ngendam am ",
  "Bangte ko'e mon",
  "Balde fumi mari haje ma",
  "Dande yeesu don ewna min",
  "Yedgo be yeesu ha asaman",
  "Mi hebi seyo ha kisnowo",
  "Mi don wara jaumirawo",
  "Yimre suwam ",
  "Bernde men seyake ngam yeesu",
  "En mayan hideko ngeden",
  "Mo'ere yeesu",
  "Babirawo allah",
  "Mi don haba habre wonde",
  "Babare fu ha yeesu krist",
  "Mi numan foroy ha allah ",
  "Teffe gikku nbongu",
  "War ha yeesu",
  "To hendu saatundu wadi",
  "A yobi kisdam am bee sadaka",
  "Nda yesu kisnowo men ",
  "To a linyi taaku maada ",
  "Dum seyo mango haa am ",
  "Nder juude ma mi halfini"
];

final fr2ful = {};
