refs = [
    "Mélodie : Jesus loves me",
    "Mélodie : Shall we gathe at the river",
    "Mélodie : Sitting at the feet of Yesus",
    "Mélodie : Nebo’s height",
    "Mélodie : Praise ye the Father",
    "Mélodie : Am I a soldier of the cross",
    "Mélodie : All the Way My Savior Leads",
    "H.L. 320: Quel ami fidèle",
    "Mélodie : Rock of ages",
    "H.L. 243: O vous qui n’avez pas la paix",
    "Mélodie : Song of victory",
    "H.L. 224 : Tel que je suis, sans rien a moi",
    "Mélodie: No not one",
    "H.L. 272: O jour heureux, jour de Bonheur",
    "Melodie : Pass me not",
    "Mélodie : 1 praise god",
    "Mélodie: Jesus keep",
    "Melodie : Lord I care not for riches",
    "H.L. 368 : Mon Dieu, plus près de toi",
    "Mèlodie: Are you washed in the blood",
    "H.L 257 : venez au sauveur qui vous aime",
    "Mélodie : He leadeth me",
    "H.L. 505 : Tout joyeux benissons le seigneur",
    "Mélodie : Lord I’m coming home",
    "Mélodie : Glory to his name",
    "Mélodie : He hideth my soul",
    "Mélodie : This love makes us happy",
    "Mélodie : Even me",
    "H.L. 565 : Le Seigneur m’aime",
    "H.L. 197 : Reste avec nous",
    "Mélodie : Rock of ages",
    "Mélodie : Jesus is coming again",
    "H.L. 290 : Dans les cieux et sur la terre",
    "H.L. 337 : Je veux, pecheur sauvé par ta grâce.",
    "H.L. 282 : Roc séculaire",
    "Mélodie : Hark ! ten thousand harps and voices.",
    "Mélodie : Children of the heavenly father",
    "H.L. 347 : Debout, sainte cohorte",
    "Mélodie : Brinfing in the sheaves",
    "Mélodie : They come from the East and West",
    "H.L. 446 : Jésus soit avec vous à jamais",
    "H.L. 215 : Entends-tu le chant joyeux",
    "H.L. 163 : Silence! Silence!",
    "Mélodie : Nailed to the cross",
    "H.L. 512 : Voir mon sauveurr face à face",
    "Mélodie : Bulu n° 4",
    "H.L. 585 : Tinte, piece blanche",
    "H.L. 199 : Que la grace de notre Seigneur Jèsus",
    "Ch. H. 447",
    "H.L. 254 : Une bone nouvelle",
    "Z.L. 580",
    "H.L. 271 : Misericorde insondable",
    "H.L. 21 : O toi dont les bienfaits",
    "H.L. 1 : Vous qui sur la terre habitez",
    "H.L. 135 : Livre sacré, lumiere étincelante",
    "H.L. 242 : Le Maître est là qui t’appelle",
    "H.L. 531 : Ecoutez l’appel du berger",
    "H.L. 403 : Marchons, frères, bon courage",
    "H.L. 432 : On n’est bien à la maison",
    "H.L. 500 : Jèsus, je te suivrai partout",
    "H.L. 128 : Comme une terre alterée",
    "Ch. De V. 304",
    "H.L. 342 : Qu’il fait bon à ton service",
    "H.L. 342 : Qu’il fait bon à ton service",
    "H.L. 560 : Jesus est au milieu de nous",
    "H.L. 347 : Debout, sainte cohorte",
    "H.L. 566 : Le Seigneur m’aime",
    "H.L. 465 : Es-tu lassé, rempli de tristesse",
    "Z.L. 996",
    "H.L. 514 : car Jèsus quand je chancelle",
    "Ch. V. 135",
    "H.L. 508 : Seigneur mon âme",
    "H.L. 561 : Je suis la lumiere",
    "H.L. 248 : Par ce chemin solitaire",
    "H.L. 237 : Pour toi j’ai donné ma vie",
    "H.L. 259 : viens au père qui t’appelle",
    "H.L. 277 : J’ai longtemps érré sans guide",
    '"H.L. 352 : Jusqu \'à la mort nous te serons fidèle"',
    "",
    "H.L. 413 : O mon Dieu je cherche ta face",
    "H.L. 407 : Pèlerin sur cette terre.",
    "H.L. 249 : Pecheur, je voudrais",
    "H.L. 495 : La voix du Seigneur t’appelle.",
    "",
    "H.L. 556 : Chaque jour de ma vie.",
    "H.L. 142 : L’Eglise est étrangere.",
    "H.L. 359 : J’ai soif de ta presence",
    "H.L. 201 : La voix du Krist nous appelle",
    "H.L. 394 : Contemplez mon Dieu sur son trône",
    "H.L. 380 : O toi mon allegresse",
    "H.L. 340 : Viens! Mon âme te reclame.",
    "H.L. 186 : Moment si doux de la prière",
    "H.L. 321 : Quel repos celeste, Jesus",
    "H.L. 449 : nous mourrons, mais pour renaître.",
    "H.L. 195 : Demeure par ta grace",
    "Ch H 688",
    "H.L. 354 : Le signal de la victoire",
    "H.L. 386 : qui me releve dans mes chutes?",
    "H.L 558 : Deux mains pour servir le maître",
    "H.L. 557 : Enfants, soyez sages",
    "H.L. 252 : viens a Jesus, il t’appelle",
    "H.L. 527 : Quand le vol de la tempête",
    "H.L. 602 : Tu payas mon salut",
    "H.L. 260 : Voici Jésus, notre Sauveur",
    "H.L. 476 : Quand tu sondes ta misère.",
    "H.L: 334 : C’est mon joyeux service",
    "H.L 489 : Entre tes mains j’abandonne",
]
